enable-module-update = true # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "anddea/revanced-patches"
patches-version = "any"
rv-brand = "anddea ReVanced"
remove-rv-integrations-checks = true
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
enabled = true
included-patches = "'Custom branding icon for YouTube'"
patcher-args = """\
  -OappIcon=mmt \
  """
patches-source = "anddea/revanced-patches"
patches-version = "any"
version = "20.13.41"
rv-brand = "anddea ReVanced"
riplib = true  
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "both"
enabled = true
version = "18.24.53"
included-patches = "'Custom branding icon for YouTube Music'"
patcher-args = """\
  -OappIcon=mmt \
  """
patches-source = "anddea/revanced-patches"
patches-version = "any"
rv-brand = "anddea ReVanced"
riplib = true
arch = "arm64-v8a"    
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
version = "latest"
arch = "arm64-v8a"
