name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # 4 AM UTC = 11 PM EST (previous day)

jobs:
  check:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest patch version from anddea/revanced-patches
        id: latest_patch
        run: |
          LATEST=$(curl -s https://api.github.com/repos/anddea/revanced-patches/releases/latest | jq -r .tag_name)
          echo "Latest patch version: $LATEST"
          echo "LATEST_PATCH=$LATEST" >> $GITHUB_OUTPUT

      - name: Should build?
        id: should_build
        shell: bash
        env:
          LATEST_PATCH: ${{ steps.latest_patch.outputs.LATEST_PATCH }}
        run: |
          if ! git checkout origin/update -- build.md; then
            echo "First build (no build.md), proceeding."
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
            exit 0
          fi

          if grep -q "anddea.*${LATEST_PATCH}" build.md; then
            echo "No update needed. Latest patch already used: ${LATEST_PATCH}"
            echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
          else
            echo "New patch release detected: ${LATEST_PATCH}"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          fi

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+10 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :

  build:
    permissions: write-all
    needs: check
    if: ${{ needs.check.outputs.SHOULD_BUILD == '1' }}
    uses: ./.github/workflows/build.yml
    with:
      from_ci: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
